//Course Actions
export const CREATE_COURSE_SUCCESS = "SAVE_COURSE_SUCCESS";
export const UPDATE_COURSE_SUCCESS = "UPDATE_COURSE_SUCCESS";
export const LOAD_COURSES_SUCCESS = "LOAD_COURSES_SUCCESS";
export const DELETE_COURSE_OPTIMISTIC = "DELETE_COURSE_OPTIMISTIC";

// Authors Actions
export const CREATE_AUTHOR_SUCCESS = "CREATE_AUTHOR_SUCCESS";
export const UPDATE_AUTHOR_SUCCESS = "UPDATE_AUTHOR_SUCCESS";
export const LOAD_AUTHORS_SUCCESS = "LOAD_AUTHORS_SUCCESS";
export const LOAD_AUTHOR_CATEGORIES_SUCCESS = "LOAD_AUTHOR_CATEGORIES_SUCCESS";
export const DELETE_AUTHOR_OPTIMISTIC = "DELETE_AUTHOR_OPTIMISTIC";
export const DELETE_AUTHOR_SUCCESS = "DELETE_AUTHOR_SUCCESS";

// Stores Actions
export const LOAD_STORES_SUCCESS = "LOAD_STORES_SUCCESS";

//API Status Actions
export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";
